train:
  trainer:
    # for cluster training
    strategy: "async"

  epochs: 10
  workspace: "paddlerec.models.rank.dnn"

  reader:
    batch_size: 512
    class: "{workspace}/../criteo_reader.py"
    train_data_path: "train_data"
    reader_debug_mode: False

  model:
    models: "{workspace}/model.py"
    hyper_parameters:
      sparse_inputs_slots: 27
      sparse_feature_number: 1000001
      sparse_feature_dim: 10
      dense_input_dim: 13
      fc_sizes: [400, 400, 400]
      learning_rate: 0.0001
      optimizer: adam

  save:
    increment:
      dirname: "increment"
      epoch_interval: 2
      save_last: True
    inference:
      dirname: "inference"
      epoch_interval: 4
      save_last: True
